FROM python:3.10-slim  

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .  

# Important: Set the working directory INSIDE the container to core_app
WORKDIR /app/core_app

CMD ["python", "sample_app.py"] 
